#!/usr/bin/env bash
set -euo pipefail

WORKSPACE=dev
TFVARS="envs/${WORKSPACE}.tfvars"

for module in network s3 ci eks; do
  echo "=== Desplegando módulo $module ==="
  cd modules/$module
  terraform init -backend-config="key=$module/terraform.tfstate"
  terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE
  terraform apply -var-file="$TFVARS" -auto-approve
  cd - > /dev/null
done



eks ( con ip de admin)
alb
>dns


╷
│ Error: ECR Repository (demo-app) not empty, consider using force_delete: operation error ECR: DeleteRepository, https response error StatusCode: 400, RequestID: 0bbf5719-ddc8-49f4-af5b-5f8ddb9c7d4a, RepositoryNotEmptyException: The repository with name 'demo-app' in registry with id '647187952873' cannot be deleted because it still contains images
│
│