#!/usr/bin/env bash
set -euo pipefail

WORKSPACE=dev
TFVARS="envs/${WORKSPACE}.tfvars"

for module in network s3 ci eks; do
  echo "=== Desplegando módulo $module ==="
  cd modules/$module
  terraform init -backend-config="key=$module/terraform.tfstate"
  terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE
  terraform apply -var-file="$TFVARS" -auto-approve
  cd - > /dev/null
done
