---
version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "647187952873"
    AWS_DEFAULT_REGION: "us-east-1"
    ECR_REPO_SERVER: "demo-app"
    ECR_REPO_CLIENT: "demo-app"
    GIT_REPO_URL: "https://github.com/gseguierjc/simetrik-demo"
    GIT_BRANCH: "main"

# Asegúrate de convertir finales de línea a LF antes de ejecutar.

phases:
  pre_build:
    commands:
      
      
      - echo "Instalando git si no está presente"
      - yum install -y git || echo "git ya instalado"
      - echo "Sparse-checkout de carpeta grpc"
      - mkdir project && cd project
      - git init
      - git remote add origin $GIT_REPO_URL
      - git config core.sparseCheckout true
      - printf 'grpc_demo/*' >> .git/info/sparse-checkout
      - git pull --depth=1 origin $GIT_BRANCH
      - cd ..
      - mv project/grpc_demo grpc_demo
      - rm -rf project
      - echo "Creando directorio para certificados"
      - mkdir -p grpc_demo/certs

      - echo "Login en Amazon ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Definiendo URIs de repositorios"
      - export REPO_URI_SERVER=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_SERVER
      - export REPO_URI_CLIENT=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_CLIENT
  build:
    commands:
      - echo "Construyendo Docker image service-server"
      - docker build --build-arg CERT_DIR=certs -t $ECR_REPO_SERVER:server -f grpc_demo/Dockerfile.server grpc_demo
      - docker tag $ECR_REPO_SERVER:server $REPO_URI_SERVER:server
      - echo "Construyendo Docker image service-client"
      - docker build --build-arg CERT_DIR=certs -t $ECR_REPO_CLIENT:client -f grpc_demo/Dockerfile.client grpc_demo
      - docker tag $ECR_REPO_CLIENT:client $REPO_URI_CLIENT:client

  post_build:
    commands:
      - echo "Pushing imágenes a ECR"
      - docker push $REPO_URI_SERVER:server
      - docker push $REPO_URI_CLIENT:client
      - echo "Creando imagedefinitions.json"
      - printf '[{"name":"service-server","imageUri":"%s"}]' $REPO_URI_SERVER:server > imagedefinitions.json
      - printf '[{"name":"service-client","imageUri":"%s"}]' $REPO_URI_CLIENT:client >> imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
