# 1) Imagen base
FROM public.ecr.aws/docker/library/python:3.11-slim


# 2) Directorio de trabajo
WORKDIR /app


# copia únicamente el paquete
COPY grpc_demo/ grpc_demo/

# instala dependencias
COPY grpc_demo/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install grpcio-health-checking
COPY certs/ grpc_demo/certs/

EXPOSE 50051

# 5) Comando por defecto
CMD ["python", "-m", "grpc_demo.server"]

