FROM public.ecr.aws/docker/library/python:3.11-slim


WORKDIR /app
COPY grpc_demo/ grpc_demo/

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY certs/ grpc_demo/certs/

# (Opcional) si tu client no necesita exponer puertos, puedes omitir EXPOSE

CMD ["python", "-m", "grpc_demo.client"]

