FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY client.py .
COPY certs/ certs/

# (Opcional) si tu client no necesita exponer puertos, puedes omitir EXPOSE

CMD ["python", "client.py"]
